[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"

[rpc_endpoints]
holesky = "${HOLESKY_RPC_URL}"

[etherscan]
holesky = { key = "${ETHERSCAN_API_KEY}", url = "https://holesky.etherscan.io/api" }